# Generated by Django 3.2.18 on 2023-03-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_database', '0002_alter_episode_stardate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='stardate',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
