# Generated by Django 3.2.18 on 2023-03-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fan_database', '0003_alter_episode_stardate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['season_episode_number']},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['season_number']},
        ),
    ]
