# Generated by Django 3.2.18 on 2023-04-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_database', '0004_auto_20230330_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='synopsis',
            field=models.TextField(default='Enter synopsis for episode'),
        ),
    ]
