# Generated by Django 3.2.18 on 2023-04-04 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fan_database', '0005_episode_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
