# Generated by Django 3.2.18 on 2023-04-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_database', '0007_deleterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleterequest',
            name='reason',
            field=models.TextField(default='Enter reason for deletion'),
        ),
    ]
