# Generated by Django 3.2.18 on 2023-04-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fan_database', '0011_episode_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deleterequest',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='approved',
        ),
        migrations.DeleteModel(
            name='ApprovalRequest',
        ),
    ]
