# Generated by Django 3.2.18 on 2023-04-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_database', '0013_auto_20230406_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
