# Generated by Django 3.2.18 on 2023-04-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fan_database', '0014_episode_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='approved',
        ),
    ]
