# Generated by Django 3.2.18 on 2023-04-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_database', '0015_remove_episode_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
