# Generated by Django 3.2.18 on 2023-04-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_database', '0016_episode_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='request_type',
            field=models.CharField(choices=[('approval', 'Approval'), ('edit', 'Edit')], default='approval', max_length=10),
            preserve_default=False,
        ),
    ]
