# Generated by Django 3.2.18 on 2023-04-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_database', '0017_approvalrequest_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='request_type',
            field=models.CharField(choices=[('approval', 'Approval'), ('edit', 'Edit')], default='approval', max_length=10),
        ),
    ]
