# Generated by Django 3.2.18 on 2023-04-08 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fan_database', '0018_alter_approvalrequest_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='object_to_approve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='fan_database.episode'),
        ),
    ]
