# Generated by Django 3.2.18 on 2023-04-09 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fan_database', '0019_alter_approvalrequest_object_to_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='reason',
            field=models.TextField(default='Enter inforamtion on the request'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='object_to_approve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fan_database.episode'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='request_type',
            field=models.CharField(choices=[('approval', 'Approval'), ('edit', 'Edit'), ('delete', 'Delete')], max_length=10),
        ),
    ]
