# Generated by Django 3.2.18 on 2023-04-10 12:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fan_database', '0020_auto_20230409_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='DeleteRequest',
        ),
    ]
