# Generated by Django 3.2.18 on 2023-04-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_database', '0021_auto_20230410_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='summary',
            field=models.TextField(default='Enter an summary on what happen in the season'),
        ),
    ]
