# Generated by Django 3.2.18 on 2023-04-15 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fan_database', '0022_season_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('overall_episode_number', models.IntegerField()),
                ('season_episode_number', models.IntegerField()),
                ('title', models.CharField(max_length=220)),
                ('synopsis', models.TextField()),
                ('air_date', models.DateField()),
                ('stardate', models.DecimalField(decimal_places=1, max_digits=6)),
                ('approved', models.BooleanField(default=False)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fan_database.episode')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fan_database.season')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
