# Generated by Django 3.2.18 on 2023-04-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_database', '0023_episodelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='plot',
            field=models.TextField(default="Write a detail description of the episode's plot, use multiple paragraphs"),
        ),
        migrations.AlterField(
            model_name='episode',
            name='synopsis',
            field=models.TextField(default='Enter synopsis for episode, keep it brief and in one paragraph'),
        ),
    ]
