# Generated by Django 3.2.18 on 2023-04-16 17:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fan_database', '0024_auto_20230416_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
