# Generated by Django 3.2.18 on 2023-04-16 17:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fan_database', '0025_episode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
