# Generated by Django 3.2.18 on 2023-04-16 18:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fan_database', '0026_alter_episode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='debug-image.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='season',
            name='image',
            field=cloudinary.models.CloudinaryField(default='debug-image.jpg', max_length=255, verbose_name='image'),
        ),
    ]
