# Generated by Django 3.2.18 on 2023-04-18 12:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_database', '0027_auto_20230416_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodelog',
            name='plot',
            field=models.TextField(default="Write a detail description of the episode's plot, use multiple paragraphs"),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
