# Generated by Django 3.2.18 on 2023-04-18 14:25

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fan_database', '0028_auto_20230418_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='object_to_approve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fan_database.episode'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='debug-image.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fan_database.season'),
        ),
        migrations.AlterField(
            model_name='episodelog',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fan_database.episode'),
        ),
        migrations.AlterField(
            model_name='episodelog',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fan_database.season'),
        ),
    ]
