# Generated by Django 3.2.18 on 2023-04-22 14:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fan_database', '0029_auto_20230418_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
